# Generated by Django 2.0.4 on 2019-01-23 10:22

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppliConfig', '0008_auto_20190123_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimodel',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='AppliConfig.ViModel'),
        ),
    ]
