# Generated by Django 2.0.4 on 2019-01-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppliConfig', '0009_auto_20190123_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vimodel',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Vimodel',
        ),
    ]
