# Generated by Django 2.0.4 on 2019-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppliConfig', '0011_vitapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitapi',
            name='key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
