# Generated by Django 2.0.4 on 2019-01-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppliConfig', '0013_auto_20190123_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitapi',
            old_name='key',
            new_name='clef',
        ),
    ]
