# Generated by Django 2.0.4 on 2019-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppliConfig', '0017_auto_20190125_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitapi',
            name='niveau',
        ),
        migrations.AddField(
            model_name='vitapi',
            name='clef',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
