# Generated by Django 2.0.4 on 2019-01-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppliConfig', '0019_auto_20190125_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitapi',
            name='ligne',
        ),
        migrations.RemoveField(
            model_name='vitapi',
            name='niveau',
        ),
    ]
